apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-test
  description: demostracion app test
  tags:
    - api-test
  links:
    - url: https://api-test.com
      title: Front End
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: user:guest