apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-component-1
  title: web-finanzas
  description: |
    Servicio de test para Backstage. Tecnologia nodejs 
  links:
    - url: https://web.com
      title: Web Front prod
      icon: dashboard
    - url: https://backend.com
      title: Backend prod
      icon: dashboard
    - url: https://util.com
      title: Microservicio Util prod
      icon: dashboard
    - url: https://dev.web.com
      title: Web Front dev
      icon: dashboard
  tags:
    - node-12
    - js
    - roble
  annotations:
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: SISTADMISION-BKOFFCAJAS-ANGULAR
    jenkins.io/job-full-name: prod:produccion/Roble-Finanzas/web-finanzas
spec:
  type: website
  owner: trebol-it
  lifecycle: production
  system: Roble-finanzas
  dependsOn:
    - Component:api-cajas
    - Resource:bd-mongo

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Backend
  name: api-cajas
  description: Servicio backend proyecto, ejemplo backstage.
spec:
  type: backend
  lifecycle: production
  owner: trebol-it
  system: Roble-finanzas
  providesApis:
    - tyk-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  title: Ejemplo Service API
  name: tyk-api-validar
  description: Servicio de API que permite ejecutar accion validar.
  tags:
    - unstable
spec:
  type: openapi
  lifecycle: production
  owner: trebol-it
  system: Roble-finanzas
  definition:
    $text: https://url-definicionapi.yaml
  subcomponentOf: api-cajas

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bd-mongo
  description: BD Mongo en cluster k8, replicaset 3 replicas.
spec:
  type: bd-mongo
  owner: trebol-it
  system: Roble-finanzas
