apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-test
  description: demostracion app test
  tags:
    - api-test
spec:
  type: service
  lifecycle: production
  owner: equipo
  system: finanzas
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api